Repository Ijaiswalshivam/Talk-In, pull requests merged in 2024-05, with the labels that each got.

#36 Create LICENSE
  LICENSE
Labels: gssoc, level1

#37 Fix #35: Default FirebaseApp is not initialized in this process com.example.talk_in.
  TalkIn/build.gradle
Labels: bug, gssoc, level2

#39 addition of necessities
  README.md
Labels: good first issue, gssoc

#43 Added Welcome Screen to improve UI
  .idea/.gitignore
  .idea/Talk-In2.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  TalkIn/.idea/vcs.xml
  TalkIn/app/.idea/.gitignore
  TalkIn/app/.idea/gradle.xml
  TalkIn/app/.idea/misc.xml
  TalkIn/app/.idea/vcs.xml
  TalkIn/app/build.gradle
  TalkIn/app/google-services.json
  TalkIn/app/src/main/AndroidManifest.xml
  TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
  TalkIn/app/src/main/res/drawable/black_rounded_corner.xml
  TalkIn/app/src/main/res/drawable/button_border.xml
  TalkIn/app/src/main/res/drawable/facebook_f.xml
  TalkIn/app/src/main/res/drawable/google.xml
  TalkIn/app/src/main/res/drawable/rounded_corners.xml
  TalkIn/app/src/main/res/drawable/twitter.xml
  TalkIn/app/src/main/res/drawable/yahoo.xml
  TalkIn/app/src/main/res/layout/activity_entry.xml
  TalkIn/app/src/main/res/layout/video_background.xml
  TalkIn/app/src/main/res/raw/bg.mp4
  TalkIn/build.gradle
  TalkIn/gradle/wrapper/gradle-wrapper.properties
Labels: enhancement, gssoc, level3

#42 UI Enhancement #21
  TalkIn/.idea/misc.xml
  TalkIn/app/src/main/res/drawable/custom_edit_text.xml
  TalkIn/app/src/main/res/layout/activity_log_in.xml
  TalkIn/app/src/main/res/layout/activity_sign_up.xml
Labels: enhancement, gssoc, level1

#40 Fix Indentation
  TalkIn/app/src/main/java/com/example/talk_in/Message.kt
  TalkIn/app/src/main/java/com/example/talk_in/MessageAdapter.kt
Labels: enhancement, good first issue, gssoc

#38 feat : Add toast to show the timestamp when the message was sent.
  TalkIn/app/src/main/java/com/example/talk_in/Message.kt
Labels: enhancement, gssoc, level1

#64 Added: transition when moving from one page to other
  TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
  TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
  TalkIn/app/src/main/res/anim/slide_in_bottom.xml
  TalkIn/app/src/main/res/anim/slide_in_from_right.xml
  TalkIn/app/src/main/res/anim/slide_out_bottom.xml
  TalkIn/app/src/main/res/anim/slide_out_to_right.xml
Labels: enhancement, gssoc, level2, feature

#61 Verification feature is added and Icon Updated #44 #45 #24
  .idea/misc.xml
  TalkIn/.idea/appInsightsSettings.xml
  TalkIn/.idea/misc.xml
  TalkIn/app/build.gradle
  TalkIn/app/src/main/AndroidManifest.xml
  TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
  TalkIn/app/src/main/res/drawable-v24/icon.jpg
  TalkIn/app/src/main/res/layout/activity_entry.xml
  TalkIn/app/src/main/res/layout/activity_log_in.xml
  TalkIn/app/src/main/res/layout/activity_sign_up.xml
Labels: enhancement, gssoc, level2

#73 Created Pull request template #72
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: documentation, gssoc, level1

#62 Bug:after logout it opens directly SigIn instead of EntryActivity
  TalkIn/.idea/compiler.xml
  TalkIn/.idea/deploymentTargetDropDown.xml
  TalkIn/.idea/gradle.xml
  TalkIn/.idea/misc.xml
  TalkIn/app/build.gradle
  TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
  TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
  TalkIn/app/src/main/res/drawable-nodpi/bg1.xml
  TalkIn/app/src/main/res/drawable/baseline_arrow_back_24.xml
  TalkIn/app/src/main/res/drawable/email.xml
  TalkIn/app/src/main/res/drawable/lock.xml
  TalkIn/app/src/main/res/layout/activity_entry.xml
  TalkIn/app/src/main/res/layout/activity_log_in.xml
  TalkIn/app/src/main/res/values-night/themes.xml
  TalkIn/app/src/main/res/values/themes.xml
  TalkIn/build.gradle
  TalkIn/gradle/wrapper/gradle-wrapper.properties
Labels: bug, gssoc, level1

#79 Dark Theme problem fixed and Login Functionality added and user flow improved(Backstack)
  TalkIn/app/build.gradle
  TalkIn/app/src/main/AndroidManifest.xml
  TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
  TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/MobileAuthActivity.kt
  TalkIn/app/src/main/res/drawable-nodpi/bg1.xml
  TalkIn/app/src/main/res/drawable/baseline_arrow_back_24.xml
  TalkIn/app/src/main/res/layout/activity_log_in.xml
  TalkIn/app/src/main/res/layout/activity_mobile_auth.xml
  TalkIn/app/src/main/res/values-night/themes.xml
Labels: enhancement, gssoc, level3

#76 SetTopAppBarColor
  TalkIn/app/src/main/res/values-night/themes.xml
  TalkIn/app/src/main/res/values/themes.xml
Labels: enhancement, good first issue, gssoc, level1

#83 Added icons to signup activity
  TalkIn/.idea/misc.xml
  TalkIn/app/src/main/res/drawable/ic_baseline_email_24.xml
  TalkIn/app/src/main/res/drawable/password_icon.png
  TalkIn/app/src/main/res/drawable/user_icon.png
  TalkIn/app/src/main/res/layout/activity_sign_up.xml
Labels: enhancement, gssoc, level2

#85 Login button bug issue in light theme #82 Issue
  TalkIn/.idea/gradle.xml
  TalkIn/app/src/main/res/values/themes.xml
Labels: enhancement, gssoc, level1

#87 Improved SignUp UI #84 issue resolved
  TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
  TalkIn/app/src/main/res/drawable/baseline_person_24.xml
  TalkIn/app/src/main/res/layout/activity_log_in.xml
  TalkIn/app/src/main/res/layout/activity_sign_up.xml
Labels: gssoc, level1

#89 Add Feature: Forgot password functionality added
  TalkIn/.idea/gradle.xml
  TalkIn/app/build.gradle
  TalkIn/app/src/main/AndroidManifest.xml
  TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
  TalkIn/app/src/main/java/com/example/talk_in/ResetPasswordActivity.kt
  TalkIn/app/src/main/res/font/andika.xml
  TalkIn/app/src/main/res/layout/activity_log_in.xml
  TalkIn/app/src/main/res/layout/activity_reset_password.xml
  TalkIn/app/src/main/res/values/colors.xml
  TalkIn/app/src/main/res/values/font_certs.xml
  TalkIn/app/src/main/res/values/preloaded_fonts.xml
Labels: enhancement, gssoc, level2

#93 Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, good first issue, gssoc, level1

#92 Update README.md
  README.md
Labels: documentation, good first issue, gssoc

#94 Email verification added to SignUp and SignIn #23 #24 #91 issues
  TalkIn/.idea/compiler.xml
  TalkIn/.idea/misc.xml
  TalkIn/app/build.gradle
  TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
  TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
Labels: enhancement, gssoc, level3, Priority

#98 POp up notification added #50 #19
  TalkIn/.idea/compiler.xml
  TalkIn/.idea/gradle.xml
  TalkIn/.idea/misc.xml
  TalkIn/.idea/vcs.xml
  TalkIn/app/build.gradle
  TalkIn/app/google-services.json
  TalkIn/app/src/main/AndroidManifest.xml
  TalkIn/app/src/main/ic_launcher-playstore.png
  TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/FCMNotificationService.kt
  TalkIn/app/src/main/java/com/example/talk_in/FcmNotificationsSender.kt
  TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
  TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
  TalkIn/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  TalkIn/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  TalkIn/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  TalkIn/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  TalkIn/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  TalkIn/build.gradle
  TalkIn/gradle.properties
  TalkIn/gradle/wrapper/gradle-wrapper.properties
Labels: enhancement, gssoc, level3

#102 feat: automate greetings using github bot
  .github/workflows/greetings.yml
Labels: documentation, gssoc, level1

#108 Updating the Group icon attaching respective activities is on the way… #9
  TalkIn/.idea/appInsightsSettings.xml
  TalkIn/.idea/misc.xml
  TalkIn/app/src/main/AndroidManifest.xml
  TalkIn/app/src/main/res/drawable/img_3.png
  TalkIn/app/src/main/res/drawable/img_4.png
  TalkIn/app/src/main/res/layout/activity_chat.xml
  TalkIn/app/src/main/res/menu/bottom_navigation_menu.xml
  TalkIn/app/src/main/res/values/strings.xml
Labels: enhancement, gssoc, level1

#107 Bottom Navigation
  TalkIn/app/src/main/res/drawable/shape_item_message_left.xml
  TalkIn/app/src/main/res/layout/activity_main.xml
  TalkIn/app/src/main/res/layout/item_message_base.xml
  TalkIn/app/src/main/res/layout/shape_item_message_left.xml
Labels: enhancement, gssoc, level2

#119 Issue #20 Web View of the application [Web App]
  .idea/misc.xml
  .idea/vcs.xml
  Talk-In Webapp/.gitignore
  Talk-In Webapp/.metadata
  Talk-In Webapp/README.md
  Talk-In Webapp/Talk-In.html
  Talk-In Webapp/analysis_options.yaml
  Talk-In Webapp/assets/images/facebook_f.PNG
  Talk-In Webapp/assets/images/google.PNG
  Talk-In Webapp/assets/images/profile.png
  Talk-In Webapp/assets/images/talkin.jpg
  Talk-In Webapp/assets/images/twitter.PNG
  Talk-In Webapp/assets/images/yahoo.PNG
  Talk-In Webapp/assets/videos/bg.gif
  Talk-In Webapp/assets/videos/bg.mp4
  Talk-In Webapp/firebase.json
  Talk-In Webapp/lib/firebase_options.dart
  Talk-In Webapp/lib/generated/assets.dart
  Talk-In Webapp/lib/main.dart
  Talk-In Webapp/lib/presentation/screens/entry_screen.dart
  Talk-In Webapp/lib/presentation/screens/find_people.dart
  Talk-In Webapp/lib/presentation/screens/home_screen.dart
  Talk-In Webapp/lib/presentation/screens/notification_screen.dart
  Talk-In Webapp/lib/presentation/screens/sign_in_screen.dart
  Talk-In Webapp/lib/presentation/screens/signup_screen.dart
  Talk-In Webapp/lib/services/auth_service.dart
  Talk-In Webapp/lib/services/data_service.dart
  Talk-In Webapp/lib/services/user_service.dart
  Talk-In Webapp/pubspec.lock
  Talk-In Webapp/pubspec.yaml
  Talk-In Webapp/test/widget_test.dart
  Talk-In Webapp/web/favicon.png
  Talk-In Webapp/web/icons/Icon-192.png
  Talk-In Webapp/web/icons/Icon-512.png
  Talk-In Webapp/web/icons/Icon-maskable-192.png
  Talk-In Webapp/web/icons/Icon-maskable-512.png
  Talk-In Webapp/web/index.html
  Talk-In Webapp/web/manifest.json
Labels: enhancement, gssoc, level3

#122 Sign In verification issue fixed
  TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
Labels: bug, gssoc, level2

#123 Fixed verification issue and email already exists issue in signup page
  TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
Labels: bug, gssoc, level3

#124 Added the Group Button and Connected the buttons to their respective fragments. Clicking Bottom buttons will work now except 1.
  TalkIn/.idea/appInsightsSettings.xml
  TalkIn/app/src/main/AndroidManifest.xml
  TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/ChatList.kt
  TalkIn/app/src/main/java/com/example/talk_in/ChatListFragment.kt
  TalkIn/app/src/main/java/com/example/talk_in/GroupFragment.kt
  TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/ProfileFragment.kt
  TalkIn/app/src/main/java/com/example/talk_in/UserProfile.kt
  TalkIn/app/src/main/res/drawable/img_3.png
  TalkIn/app/src/main/res/drawable/img_4.png
  TalkIn/app/src/main/res/layout/activity_chat.xml
  TalkIn/app/src/main/res/layout/activity_chat_list.xml
  TalkIn/app/src/main/res/layout/activity_main.xml
  TalkIn/app/src/main/res/layout/activity_user_profile.xml
  TalkIn/app/src/main/res/layout/fragment_chat_list.xml
  TalkIn/app/src/main/res/layout/fragment_group.xml
  TalkIn/app/src/main/res/layout/fragment_profile.xml
  TalkIn/app/src/main/res/menu/bottom_navigation_menu.xml
  TalkIn/app/src/main/res/values/strings.xml
Labels: enhancement, gssoc, level3

#126 Mobile Number Verification screen Added
  TalkIn/.idea/gradle.xml
  TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
  TalkIn/app/src/main/java/com/example/talk_in/MobileAuthActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
  TalkIn/app/src/main/res/drawable/baseline_phone_iphone_24.xml
  TalkIn/app/src/main/res/layout/activity_mobile_auth.xml
Labels: enhancement, gssoc, level2

#127 Verification is removed from login page
  TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
Labels: bug, gssoc, level2

#128 Readme update regarding Deploying of the TalkIn Web App using Firebase Hosting
  .idea/vcs.xml
  README.md
Labels: documentation, gssoc, level1

#129 All users will now be displayed on Chat activity.
  TalkIn/app/src/main/java/com/example/talk_in/ChatListFragment.kt
Labels: bug, gssoc, level1

#132 Issue #120 Messaging feature between users in the Web App
  Talk-In Webapp/lib/presentation/screens/home_screen.dart
  Talk-In Webapp/lib/presentation/screens/messaging_screen.dart
  Talk-In Webapp/lib/presentation/screens/notification_screen.dart
  Talk-In Webapp/lib/services/auth_service.dart
  Talk-In Webapp/lib/services/data_service.dart
  Talk-In Webapp/pubspec.lock
  Talk-In Webapp/pubspec.yaml
Labels: enhancement, gssoc, level3

#139 Progress bar added on login and signup
  TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
  TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
  TalkIn/app/src/main/res/layout/activity_log_in.xml
  TalkIn/app/src/main/res/layout/activity_sign_up.xml
Labels: enhancement, gssoc, level1

#149 Issue #140 Add UI Fixes like progress bar in web app along with View Models
  .idea/Talk-In2.iml
  Talk-In Webapp/lib/main.dart
  Talk-In Webapp/lib/presentation/screens/find_people.dart
  Talk-In Webapp/lib/presentation/screens/home_screen.dart
  Talk-In Webapp/lib/presentation/screens/notification_screen.dart
  Talk-In Webapp/lib/presentation/screens/sign_in_screen.dart
  Talk-In Webapp/lib/presentation/screens/signup_screen.dart
  Talk-In Webapp/lib/services/auth_service.dart
  Talk-In Webapp/lib/services/data_service.dart
  Talk-In Webapp/pubspec.lock
  Talk-In Webapp/pubspec.yaml
Labels: enhancement, gssoc, level3

#152 Improvement in UI of Mobile Authentication screen, chat screen and added search bar functionality
  TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/MessageAdapter.kt
  TalkIn/app/src/main/java/com/example/talk_in/MobileAuthActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/UserAdapter.kt
  TalkIn/app/src/main/res/drawable/background_image_chat.jpg
  TalkIn/app/src/main/res/drawable/edt_background2.xml
  TalkIn/app/src/main/res/drawable/message_box_background.xml
  TalkIn/app/src/main/res/drawable/popup_menu_icon.png
  TalkIn/app/src/main/res/drawable/send_icon.png
  TalkIn/app/src/main/res/layout/activity_chat.xml
  TalkIn/app/src/main/res/layout/activity_main.xml
  TalkIn/app/src/main/res/layout/activity_mobile_auth.xml
  TalkIn/app/src/main/res/layout/receive.xml
  TalkIn/app/src/main/res/menu/user_chat_menu.xml
Labels: enhancement, gssoc, level3

#157 Fcm Notification added #19, #138, #110
  TalkIn/.idea/deploymentTargetSelector.xml
  TalkIn/app/build.gradle
  TalkIn/app/src/main/AndroidManifest.xml
  TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/FCMNotificationService.kt
  TalkIn/app/src/main/java/com/example/talk_in/FcmNotificationsSender.kt
  TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
  TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/ResetPasswordActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
  TalkIn/app/src/main/res/layout/receive.xml
  TalkIn/app/src/main/res/layout/sent.xml
  TalkIn/app/src/main/res/values/strings.xml
Labels: gssoc, level3

#158 Locate Now button added on chat activity
  TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
  TalkIn/app/src/main/res/menu/user_chat_menu.xml
Labels: gssoc, level2

#160 Issue #153 Setting tab in web app
  Talk-In Webapp/lib/presentation/screens/find_people.dart
  Talk-In Webapp/lib/presentation/screens/home_screen.dart
  Talk-In Webapp/lib/presentation/screens/settings_screen.dart
  Talk-In Webapp/lib/services/auth_service.dart
  Talk-In Webapp/lib/services/data_service.dart
  Talk-In Webapp/pubspec.lock
  Talk-In Webapp/pubspec.yaml
  Talk-In Webapp/web/index.html
Labels: gssoc, level3

#161 Mobile number authentication added
  TalkIn/app/src/main/java/com/example/talk_in/MobileAuthActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
  TalkIn/app/src/main/java/com/example/talk_in/User.kt
  TalkIn/app/src/main/res/layout/activity_mobile_auth.xml
  TalkIn/app/src/main/res/layout/activity_sign_up.xml
Labels: gssoc, level3, feature

#155 Track Location of Chatting User Talk-IN
  .idea/misc.xml
  TalkIn/.idea/deploymentTargetSelector.xml
  TalkIn/app/build.gradle
  TalkIn/app/src/main/AndroidManifest.xml
  TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
  TalkIn/app/src/main/res/layout/activity_chat.xml
  TalkIn/app/src/main/res/menu/user_chat_menu.xml
Labels: gssoc, level3

#168 FCm Notifications added and etc. #19 #110 #138
  TalkIn/.idea/gradle.xml
  TalkIn/.idea/misc.xml
  TalkIn/.idea/vcs.xml
  TalkIn/app/build.gradle
  TalkIn/app/src/main/AndroidManifest.xml
  TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/FCMNotificationService.kt
  TalkIn/app/src/main/java/com/example/talk_in/FcmNotificationsSender.kt
  TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
  TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
  TalkIn/app/src/main/res/layout/receive.xml
  TalkIn/app/src/main/res/layout/sent.xml
  TalkIn/app/src/main/res/values/strings.xml
Labels: enhancement, gssoc, level3

#167 Profile Screen added
  TalkIn/.idea/deploymentTargetDropDown.xml
  TalkIn/app/src/main/AndroidManifest.xml
  TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/UserProfileScreen.kt
  TalkIn/app/src/main/res/drawable/circular_grey_border_solid.xml
  TalkIn/app/src/main/res/drawable/circularbordersolid.xml
  TalkIn/app/src/main/res/drawable/circularbordersolidblack.xml
  TalkIn/app/src/main/res/drawable/edit_icon.png
  TalkIn/app/src/main/res/drawable/ic_arrow_back_24dp.xml
  TalkIn/app/src/main/res/drawable/ic_call_24dp.xml
  TalkIn/app/src/main/res/drawable/ic_email_24dp.xml
  TalkIn/app/src/main/res/drawable/profile_picture_border.xml
  TalkIn/app/src/main/res/font/proximanovaregular.otf
  TalkIn/app/src/main/res/layout/activity_user_profile_screen.xml
  TalkIn/app/src/main/res/menu/menu.xml
  TalkIn/app/src/main/res/values/strings.xml
Labels: enhancement, gssoc, level3

#175 Profile Screen added
  TalkIn/.idea/deploymentTargetDropDown.xml
  TalkIn/app/src/main/AndroidManifest.xml
  TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/UserProfileScreen.kt
  TalkIn/app/src/main/res/drawable/circular_grey_border_solid.xml
  TalkIn/app/src/main/res/drawable/circularbordersolid.xml
  TalkIn/app/src/main/res/drawable/circularbordersolidblack.xml
  TalkIn/app/src/main/res/drawable/edit_icon.png
  TalkIn/app/src/main/res/drawable/ic_arrow_back_24dp.xml
  TalkIn/app/src/main/res/drawable/ic_call_24dp.xml
  TalkIn/app/src/main/res/drawable/ic_email_24dp.xml
  TalkIn/app/src/main/res/drawable/profile_picture_border.xml
  TalkIn/app/src/main/res/font/proximanovaregular.otf
  TalkIn/app/src/main/res/layout/activity_user_profile_screen.xml
  TalkIn/app/src/main/res/menu/menu.xml
  TalkIn/app/src/main/res/values/strings.xml
Labels: enhancement, gssoc, level3

#176 Issue #166 Google, Facebook, Twitter and Yahoo Authentication in Web App
  Talk-In Webapp/lib/presentation/screens/entry_screen.dart
  Talk-In Webapp/lib/services/auth_service.dart
  Talk-In Webapp/pubspec.lock
  Talk-In Webapp/pubspec.yaml
  Talk-In Webapp/web/index.html
Labels: enhancement, gssoc, level3

#178 Toggle button added on profile screen for permission of location by user
  TalkIn/app/src/main/java/com/example/talk_in/MobileAuthActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
  TalkIn/app/src/main/java/com/example/talk_in/User.kt
  TalkIn/app/src/main/java/com/example/talk_in/UserProfileScreen.kt
  TalkIn/app/src/main/res/layout/activity_user_profile_screen.xml
Labels: enhancement, gssoc, level2

#183 Added Authentication with google in Kotlin app
  TalkIn/app/build.gradle
  TalkIn/app/google-services.json
  TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
Labels: gssoc, level3

#192 Issue #177 Send media in message screen to other user in web app
  Talk-In Webapp/lib/presentation/screens/messaging_screen.dart
  Talk-In Webapp/lib/services/data_service.dart
  Talk-In Webapp/pubspec.lock
  Talk-In Webapp/pubspec.yaml
Labels: enhancement, level2

#194 Updated Code to Use Viewbinding
  .idea/misc.xml
  TalkIn/app/.idea/gradle.xml
  TalkIn/app/.idea/misc.xml
  TalkIn/app/.idea/modules.xml
  TalkIn/app/build.gradle
  TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
  TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/MobileAuthActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/ResetPasswordActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
  TalkIn/app/src/main/java/com/example/talk_in/UserProfileScreen.kt
Labels: gssoc, level2

#197 Fixed: User Profile Screen will show receiver users profile when clicked on view profile
  TalkIn/app/src/main/java/com/example/talk_in/UserProfileScreen.kt
Labels: bug, gssoc, level1

#200 Msg Time & Date Stamp feature implemented and Device Tokens handle is fixed. #199 #170
  TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/FCMNotificationService.kt
  TalkIn/app/src/main/java/com/example/talk_in/FcmNotificationsSender.kt
  TalkIn/app/src/main/java/com/example/talk_in/Message.kt
  TalkIn/app/src/main/java/com/example/talk_in/MessageAdapter.kt
  TalkIn/app/src/main/java/com/example/talk_in/UserProfileScreen.kt
  TalkIn/app/src/main/res/layout/date_section.xml
  TalkIn/app/src/main/res/layout/receive.xml
  TalkIn/app/src/main/res/layout/sent.xml
Labels: gssoc, level3

#202 Fix: User can update his about section and on mainactivity user's profile picture will be shown
  TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/MobileAuthActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
  TalkIn/app/src/main/java/com/example/talk_in/User.kt
  TalkIn/app/src/main/java/com/example/talk_in/UserAdapter.kt
  TalkIn/app/src/main/java/com/example/talk_in/UserProfileScreen.kt
  TalkIn/app/src/main/res/layout/activity_user_profile_screen.xml
  TalkIn/app/src/main/res/layout/custom_dialog_layout.xml
Labels: gssoc, level2

#206 App ShutDown For Android 12 and Above fixed #203
  TalkIn/app/src/main/java/com/example/talk_in/FCMNotificationService.kt
Labels: bug, gssoc, level2

#209 Issue #204 Users can view other people profile
  Talk-In Webapp/lib/presentation/screens/messaging_screen.dart
  Talk-In Webapp/lib/presentation/screens/profile_screen.dart
  Talk-In Webapp/lib/presentation/screens/settings_screen.dart
  Talk-In Webapp/pubspec.lock
  Talk-In Webapp/pubspec.yaml
Labels: enhancement, gssoc, level2

#212 Issue #205 add time stamp in message
  Talk-In Webapp/lib/presentation/screens/messaging_screen.dart
Labels: enhancement, gssoc, level1

#210 Fixed: User will not be able to see main activity after logout
  TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
  TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/MobileAuthActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/UserProfileScreen.kt
Labels: enhancement, gssoc, level1

#214 Issue #213 Forgot Password feature in web app
  Talk-In Webapp/lib/presentation/screens/sign_in_screen.dart
  Talk-In Webapp/lib/services/auth_service.dart
Labels: enhancement, gssoc, level1

#215 Fix: Unverified users will not be displayed on mainactivity
  TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/LogIn.kt
  TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/MobileAuthActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
  TalkIn/app/src/main/java/com/example/talk_in/User.kt
  TalkIn/app/src/main/java/com/example/talk_in/UserProfileScreen.kt
Labels: bug, gssoc, level2

#217 Issue #216 Unfriend functionality in web app
  Talk-In Webapp/lib/presentation/screens/find_people.dart
  Talk-In Webapp/lib/services/data_service.dart
Labels: enhancement, gssoc, level1

#226 Issue #219 Multi language model in web app
  Talk-In Webapp/lib/generated/intl/messages_all.dart
  Talk-In Webapp/lib/generated/intl/messages_en.dart
  Talk-In Webapp/lib/generated/intl/messages_hi.dart
  Talk-In Webapp/lib/generated/l10n.dart
  Talk-In Webapp/lib/l10n.yaml
  Talk-In Webapp/lib/l10n/intl_en.arb
  Talk-In Webapp/lib/l10n/intl_hi.arb
  Talk-In Webapp/lib/main.dart
  Talk-In Webapp/lib/presentation/screens/entry_screen.dart
  Talk-In Webapp/lib/presentation/screens/find_people.dart
  Talk-In Webapp/lib/presentation/screens/home_screen.dart
  Talk-In Webapp/lib/presentation/screens/messaging_screen.dart
  Talk-In Webapp/lib/presentation/screens/notification_screen.dart
  Talk-In Webapp/lib/presentation/screens/profile_screen.dart
  Talk-In Webapp/lib/presentation/screens/settings_screen.dart
  Talk-In Webapp/lib/presentation/screens/sign_in_screen.dart
  Talk-In Webapp/lib/presentation/screens/signup_screen.dart
  Talk-In Webapp/lib/services/language_service.dart
  Talk-In Webapp/pubspec.lock
  Talk-In Webapp/pubspec.yaml
Labels: gssoc, level2

#229 for chat with a person in the chatactivity notification will not be shown for that person and Bug fixed when notification received #221 #228
  TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/FCMNotificationService.kt
Labels: gssoc, level2

#234 Chat UI Fixed #231
  TalkIn/app/src/main/res/layout/receive.xml
  TalkIn/app/src/main/res/layout/sent.xml
Labels: gssoc, level2

#232 Add: Last message of the chat between sender and receiver will be showing
  TalkIn/app/src/main/java/com/example/talk_in/UserAdapter.kt
  TalkIn/app/src/main/res/layout/user_layout.xml
Labels: gssoc, level1
