Repository Ijaiswalshivam/Talk-In, pull requests merged in 2024-06, with the labels that each got.

#240 update user_layout.xml , Fixed #239
  TalkIn/app/src/main/res/layout/user_layout.xml
Labels: bug, gssoc, level2

#242 Fix: User is not able to see receiver user's profile and also user is not able to see profile picture of receiver user while chatting with them
  TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
Labels: bug, gssoc, level1

#241 Issue #238 Splash screen in web app
  Talk-In Webapp/lib/main.dart
  Talk-In Webapp/lib/presentation/screens/splash_screen.dart
Labels: gssoc, level1

#243 Fixed: User is not able to update his about me section in his profile
  TalkIn/app/src/main/java/com/example/talk_in/UserProfileScreen.kt
  TalkIn/app/src/main/res/layout/activity_user_profile_screen.xml
Labels: gssoc, level1

#250 Add: Message Encryption and Decryption added
  TalkIn/app/src/main/java/com/example/talk_in/AESUtils.java
  TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/Message.kt
  TalkIn/app/src/main/java/com/example/talk_in/MessageAdapter.kt
  TalkIn/app/src/main/java/com/example/talk_in/UserAdapter.kt
Labels: gssoc, level2

#248 Update README.md
  README.md
Labels: gssoc, level1

#257 Fixed: Message Encryption and Decryption in android application
  TalkIn/app/src/main/java/com/example/talk_in/AESUtils.java
  TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/FcmNotificationsSender.kt
  TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/Message.kt
  TalkIn/app/src/main/java/com/example/talk_in/MessageAdapter.kt
  TalkIn/app/src/main/java/com/example/talk_in/NotificationReceiver.kt
  TalkIn/app/src/main/java/com/example/talk_in/UserAdapter.kt
Labels: bug, gssoc, level2

#259 Fixed: Profile picture in chat activity & in main activity is not properly displayed
  TalkIn/app/src/main/java/com/example/talk_in/UserAdapter.kt
  TalkIn/app/src/main/res/layout/activity_chat.xml
  TalkIn/app/src/main/res/layout/user_layout.xml
Labels: bug, gssoc, level1

#260 Issue #245 message encryption in web app
  Talk-In Webapp/lib/presentation/screens/group_chat_screen.dart
  Talk-In Webapp/lib/presentation/screens/messaging_screen.dart
  Talk-In Webapp/lib/services/encryption_service.dart
Labels: enhancement, gssoc, level2

#261 Major Improvements in the User Profile Page #249
  TalkIn/.idea/appInsightsSettings.xml
  TalkIn/app/build.gradle
  TalkIn/app/src/main/java/com/example/talk_in/UserProfileScreen.kt
  TalkIn/app/src/main/res/drawable/camera_icon_profile.png
  TalkIn/app/src/main/res/drawable/default_profile_image.png
  TalkIn/app/src/main/res/drawable/error_profile_image.png
  TalkIn/app/src/main/res/layout/activity_user_profile_screen.xml
  TalkIn/app/src/main/res/layout/custom_dialog_phone_layout.xml
Labels: gssoc, level2

#273 Notification decrypt and internet error fixed #258 #264
  TalkIn/app/src/main/java/com/example/talk_in/AESUtils.java
  TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/FCMNotificationService.kt
  TalkIn/app/src/main/java/com/example/talk_in/NotificationReceiver.kt
  TalkIn/app/src/main/java/com/example/talk_in/UserAdapter.kt
Labels: gssoc, level2

#272 Obscure Password functionality in android app
  TalkIn/app/src/main/res/drawable/baseline_remove_red_eye_24.xml
  TalkIn/app/src/main/res/layout/activity_log_in.xml
  TalkIn/app/src/main/res/layout/activity_sign_up.xml
Labels: enhancement, gssoc, level1

#268 Fixed: In mainactivity name is not showing properly
  TalkIn/app/src/main/java/com/example/talk_in/UserAdapter.kt
  TalkIn/app/src/main/res/layout/user_layout.xml
Labels: bug, gssoc, level1

#276 Fix: Search bar modification
  TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
  TalkIn/app/src/main/res/drawable/custom_searchbar_background.xml
  TalkIn/app/src/main/res/layout/activity_main.xml
Labels: gssoc, level1

#275 Issue #274 Resolve Google Auth error
  TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
  TalkIn/app/src/main/res/values/strings.xml
Labels: gssoc

#278 Talk in ID feature is now live.
  TalkIn/app/src/main/java/com/example/talk_in/EntryActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/MobileAuthActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
  TalkIn/app/src/main/java/com/example/talk_in/User.kt
  TalkIn/app/src/main/res/layout/activity_mobile_auth.xml
  TalkIn/app/src/main/res/layout/activity_sign_up.xml
Labels: gssoc, level2

#284 Fixed: Signup page should ask for confirm password
  TalkIn/app/src/main/java/com/example/talk_in/SignUp.kt
  TalkIn/app/src/main/res/layout/activity_sign_up.xml
Labels: gssoc, level2, feature

#285 Add: Create group feature in android app
  TalkIn/app/src/main/AndroidManifest.xml
  TalkIn/app/src/main/java/com/example/talk_in/CreateGroupActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/DisplayGroupAdapter.kt
  TalkIn/app/src/main/java/com/example/talk_in/Group.kt
  TalkIn/app/src/main/java/com/example/talk_in/GroupChatActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/GroupMemberSelection.kt
  TalkIn/app/src/main/java/com/example/talk_in/GroupMemberSelectionAdapter.kt
  TalkIn/app/src/main/java/com/example/talk_in/Groups.kt
  TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
  TalkIn/app/src/main/res/drawable/icon_select_group_member.png
  TalkIn/app/src/main/res/drawable/plus_icon.png
  TalkIn/app/src/main/res/drawable/right_arrow_icon.png
  TalkIn/app/src/main/res/layout/activity_create_group.xml
  TalkIn/app/src/main/res/layout/activity_group_member_selection.xml
  TalkIn/app/src/main/res/layout/activity_groups.xml
  TalkIn/app/src/main/res/layout/user_layout.xml
  TalkIn/app/src/main/res/menu/bottom_navigation_menu.xml
Labels: gssoc, level3

#293 Delete For Me and Delete For Every one features is implemented. #253
  TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
  TalkIn/app/src/main/java/com/example/talk_in/Message.kt
  TalkIn/app/src/main/java/com/example/talk_in/MessageAdapter.kt
  TalkIn/app/src/main/res/drawable/copy.xml
  TalkIn/app/src/main/res/drawable/delete.xml
  TalkIn/app/src/main/res/drawable/reply.xml
  TalkIn/app/src/main/res/drawable/unsend.xml
  TalkIn/app/src/main/res/layout/custom_context_menu.xml
  TalkIn/app/src/main/res/layout/receive.xml
  TalkIn/app/src/main/res/layout/sent.xml
  TalkIn/app/src/main/res/values/colors.xml
  TalkIn/app/src/main/res/values/strings.xml
Labels: gssoc, level3
